export const SET_DATE_RANGE = 'SET_DATE_RANGE';
// export const RESET = 'RESET';
export const LOAD_QUAKE_DATA = 'LOAD_QUAKE_DATA';
export const LOAD_QUAKE_DATA_COMPLETED = 'LOAD_QUAKE_DATA_COMPLETED';
export const LOAD_QUAKE_DATA_FAILED = 'LOAD_QUAKE_DATA_FAILED';